services:
  postgres:
    image: postgres:latest
    container_name: budgetbook-postgres
    environment:
      POSTGRES_DB: budgetbook
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"