spring.application.name=budgetbookk

spring.datasource.url=jdbc:h2:file:./data/meinedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=localhost
spring.datasource.password=localhost

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console