spring.datasource.url=jdbc:postgresql://localhost:5432/budgetbook
spring.datasource.username=dbuser
spring.datasource.password=dbpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true